#!/bin/bash
#SBATCH -N 1
#SBATCH --partition=batch
#SBATCH -J train_yolov5_gpus
#SBATCH -o train_yolov5_gpus.%j.out
#SBATCH -e train_yolov5_gpus.%j.err
#SBATCH --mail-user=rui.li@kaust.edu.sa
#SBATCH --mail-type=ALL
#SBATCH --time=120:00:00
#SBATCH --mem=32G
#SBATCH --gres=gpu:v100:8
#SBATCH --constraint=[gpu]&[local_200G]

#python train_Sepnet.py
python -m torch.distributed.launch --nproc_per_node 8 train.py --epochs 50 --batch-size 16 --data /home/lir0b/Code/data/video/impact_det_ibex.yaml --weights yolov5x.pt --img 1280 --hyp hyp_impact_det.yaml

#python train.py --img 1280 --batch 4 --epochs 10 --data /home/lir0b/Code/data/video/impact_det_ibex.yaml --weights yolov5x.pt